name: municipality_app
description: Municipality services app with offline support
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Networking
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # UI/UX
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  photo_view: ^0.14.0
  
  # PDF
  # syncfusion_flutter_pdfviewer: ^30.2.6
  printing: ^5.12.0
  
  # Utils
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  intl: ^0.18.1
  
  # Icons
  cupertino_icons: ^1.0.6
  sqflite: ^2.4.1
  floor: ^1.4.1
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  iconsax: ^0.0.8
  google_fonts: ^6.3.0
  drift_flutter: ^0.2.5
  carousel_slider: ^5.1.1
  flutter_shimmer: ^2.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  hive_generator: ^2.0.1
  floor_generator: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/icons/
    - assets/images/onboarding/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700